# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-07 20:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_history', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='songs',
            options={'ordering': ('title',)},
        ),
        migrations.RemoveField(
            model_name='album',
            name='linenos',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='linenos',
        ),
        migrations.RemoveField(
            model_name='songs',
            name='linenos',
        ),
        migrations.RemoveField(
            model_name='songs',
            name='name',
        ),
        migrations.AlterField(
            model_name='songs',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
